name: Caller Workflow

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: step 4 - Build project with Maven
        run: mvn clean test --file pom.xml
